/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Zipbap Service API
 * 집밥 서비스 전용 Swagger 문서
 * OpenAPI spec version: 1.0.1
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type { LikeResponseDto } from '../zipbapServiceAPI.schemas';

export const getRecipeLike = () => {
  /**
   * 특정 레시피에 좋아요를 추가합니다.
   * @summary 레시피 좋아요 추가
   */
  const likeRecipe = <TData = AxiosResponse<LikeResponseDto>>(
    recipeId: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(`https://zipbap.store/api/recipes/${recipeId}/likes`, undefined, options);
  };
  /**
   * 특정 레시피에 누른 좋아요를 취소합니다.
   * @summary 레시피 좋아요 취소
   */
  const unlikeRecipe = <TData = AxiosResponse<LikeResponseDto>>(
    recipeId: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.delete(`https://zipbap.store/api/recipes/${recipeId}/likes`, options);
  };
  /**
   * 특정 레시피의 좋아요 개수를 조회합니다.
   * @summary 레시피 좋아요 개수 조회
   */
  const countLikes = <TData = AxiosResponse<LikeResponseDto>>(
    recipeId: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`https://zipbap.store/api/recipes/${recipeId}/likes/count`, options);
  };
  return { likeRecipe, unlikeRecipe, countLikes };
};
export type LikeRecipeResult = AxiosResponse<LikeResponseDto>;
export type UnlikeRecipeResult = AxiosResponse<LikeResponseDto>;
export type CountLikesResult = AxiosResponse<LikeResponseDto>;
