/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Zipbap Service API
 * 집밥 서비스 전용 Swagger 문서
 * OpenAPI spec version: 1.0.1
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type { PresignedUrlRequest, PresignedUrlResponse } from '../zipbapServiceAPI.schemas';

export const getFileController = () => {
  /**
 * 
            프론트가 직접 S3에 업로드할 수 있는 URL을 발급합니다.
            
            ✅ 사용 흐름
            1. 이 API 호출 → uploadUrl, fileUrl 발급
            2. 프론트에서 uploadUrl로 PUT 요청 (파일 업로드)
            3. 업로드 성공 후 fileUrl을 백엔드 레시피 API에 전달
        
 * @summary Presigned URL 발급
 */
  const generatePresignedUrl = <TData = AxiosResponse<PresignedUrlResponse>>(
    presignedUrlRequest: PresignedUrlRequest,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(`https://zipbap.store/api/files/presigned-url`, presignedUrlRequest, options);
  };
  return { generatePresignedUrl };
};
export type GeneratePresignedUrlResult = AxiosResponse<PresignedUrlResponse>;
