/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Zipbap Service API
 * 집밥 서비스 전용 Swagger 문서
 * OpenAPI spec version: 1.0.1
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type { CategoryListResponseDto, GetAllCategoriesParams } from '../zipbapServiceAPI.schemas';

export const getCategory = () => {
  /**
   * 모든 카테고리 정보를 조회합니다. (내 카테고리는 userId 기준)
   * @summary 모든 카테고리 조회
   */
  const getAllCategories = <TData = AxiosResponse<CategoryListResponseDto>>(
    params: GetAllCategoriesParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`https://zipbap.store/categories`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  return { getAllCategories };
};
export type GetAllCategoriesResult = AxiosResponse<CategoryListResponseDto>;
