/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Zipbap Service API
 * 집밥 서비스 전용 Swagger 문서
 * OpenAPI spec version: 1.0.1
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type {
  ApiResponseFollowCountDto,
  ApiResponseListFollowUserDto,
  GetFollowerListParams,
  GetFollowingListParams,
} from '../zipbapServiceAPI.schemas';

export const getFollowController = () => {
  const followUser = <TData = AxiosResponse<ApiResponseFollowCountDto>>(
    followingId: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(`https://zipbap.store/api/follows/${followingId}`, undefined, options);
  };
  const getFollowingList = <TData = AxiosResponse<ApiResponseListFollowUserDto>>(
    userId: number,
    params?: GetFollowingListParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`https://zipbap.store/api/follows/${userId}/following-list`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  const getFollowerList = <TData = AxiosResponse<ApiResponseListFollowUserDto>>(
    userId: number,
    params?: GetFollowerListParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`https://zipbap.store/api/follows/${userId}/follower-list`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  const countFollow = <TData = AxiosResponse<ApiResponseFollowCountDto>>(
    userId: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`https://zipbap.store/api/follows/${userId}/count`, options);
  };
  const unfollowUser = <TData = AxiosResponse<ApiResponseFollowCountDto>>(
    unfollowingId: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.delete(`https://zipbap.store/api/follows/${unfollowingId}`, options);
  };
  return { followUser, getFollowingList, getFollowerList, countFollow, unfollowUser };
};
export type FollowUserResult = AxiosResponse<ApiResponseFollowCountDto>;
export type GetFollowingListResult = AxiosResponse<ApiResponseListFollowUserDto>;
export type GetFollowerListResult = AxiosResponse<ApiResponseListFollowUserDto>;
export type CountFollowResult = AxiosResponse<ApiResponseFollowCountDto>;
export type UnfollowUserResult = AxiosResponse<ApiResponseFollowCountDto>;
