import type { FeedItem } from '@entities/feed/model/feedTypes';

export const dummyFeeds: FeedItem[] = [
  {
    id: '1',
    profileImage: 'https://placekitten.com/100/100',
    nickname: 'Grace',
    title: '할머니의 사과파이',
    views: 123,
    mainImage: 'https://placekitten.com/400/300',
    content: '중조 할머니부터 내려왔던 전통 레시피! 바삭한 껍질과 달콤한 사과 맛이 특징입니다.',
    cookingTime: 10,
    difficulty: '쉬움',
    ingredientsCount: 15,
    likes: 45,
    bookmarks: 67,
    comments: 45,
    isLiked: false,
    isBookmarked: false,
    isCommented: false,
  },
  {
    id: '2',
    profileImage: 'https://placekitten.com/101/101',
    nickname: 'Minji',
    title: '김치볶음밥',
    views: 256,
    mainImage: 'https://placekitten.com/401/301',
    content: '간단하고 맛있는 한 끼! 집에 있는 재료로 쉽게 만들 수 있어요.',
    cookingTime: 20,
    difficulty: '보통',
    ingredientsCount: 8,
    likes: 120,
    bookmarks: 34,
    comments: 20,
    isLiked: true,
    isBookmarked: false,
    isCommented: false,
  },
  {
    id: '3',
    profileImage: 'https://placekitten.com/102/102',
    nickname: 'Chef Park',
    title: '스테이크와 구운 채소',
    views: 512,
    mainImage: 'https://placekitten.com/402/302',
    content: '육즙 가득한 스테이크와 신선한 채소의 조화! 특별한 날에 딱 맞는 메뉴입니다.',
    cookingTime: 40,
    difficulty: '어려움',
    ingredientsCount: 12,
    likes: 300,
    bookmarks: 120,
    comments: 55,
    isLiked: false,
    isBookmarked: false,
    isCommented: false,
  },
  {
    id: '4',
    profileImage: 'https://placekitten.com/103/103',
    nickname: 'Jiwon',
    title: '된장찌개',
    views: 180,
    mainImage: 'https://placekitten.com/403/303',
    content: '한국인의 소울푸드, 구수한 된장찌개 한 그릇!',
    cookingTime: 25,
    difficulty: '쉬움',
    ingredientsCount: 10,
    likes: 95,
    bookmarks: 22,
    comments: 12,
    isLiked: false,
    isBookmarked: false,
    isCommented: false,
  },
  {
    id: '5',
    profileImage: 'https://placekitten.com/104/104',
    nickname: 'Hana',
    title: '토마토 파스타',
    views: 342,
    mainImage: 'https://placekitten.com/404/304',
    content: '새콤달콤 토마토 소스로 만든 정통 이탈리안 파스타.',
    cookingTime: 30,
    difficulty: '보통',
    ingredientsCount: 9,
    likes: 210,
    bookmarks: 80,
    comments: 33,
    isLiked: false,
    isBookmarked: false,
    isCommented: false,
  },
  {
    id: '6',
    profileImage: 'https://placekitten.com/105/105',
    nickname: 'Junho',
    title: '불고기',
    views: 478,
    mainImage: 'https://placekitten.com/405/305',
    content: '달콤짭조름한 양념에 재운 소고기를 불향 가득하게 구워낸 불고기.',
    cookingTime: 35,
    difficulty: '보통',
    ingredientsCount: 11,
    likes: 276,
    bookmarks: 110,
    comments: 44,
    isLiked: false,
    isBookmarked: false,
    isCommented: false,
  },
  {
    id: '7',
    profileImage: 'https://placekitten.com/106/106',
    nickname: 'Seoyun',
    title: '마카롱',
    views: 150,
    mainImage: 'https://placekitten.com/406/306',
    content: '겉은 바삭, 속은 촉촉한 프랑스 디저트 마카롱.',
    cookingTime: 50,
    difficulty: '어려움',
    ingredientsCount: 7,
    likes: 98,
    bookmarks: 60,
    comments: 25,
    isLiked: false,
    isBookmarked: false,
    isCommented: false,
  },
  {
    id: '8',
    profileImage: 'https://placekitten.com/107/107',
    nickname: 'David',
    title: '치즈버거',
    views: 600,
    mainImage: 'https://placekitten.com/407/307',
    content: '두툼한 패티와 치즈, 신선한 채소가 어우러진 수제 치즈버거.',
    cookingTime: 20,
    difficulty: '쉬움',
    ingredientsCount: 6,
    likes: 330,
    bookmarks: 140,
    comments: 62,
    isLiked: false,
    isBookmarked: false,
    isCommented: false,
  },
  {
    id: '9',
    profileImage: 'https://placekitten.com/108/108',
    nickname: 'Sujin',
    title: '떡볶이',
    views: 720,
    mainImage: 'https://placekitten.com/408/308',
    content: '매콤달콤 한국 대표 길거리 음식, 떡볶이!',
    cookingTime: 15,
    difficulty: '쉬움',
    ingredientsCount: 5,
    likes: 410,
    bookmarks: 160,
    comments: 72,
    isLiked: false,
    isBookmarked: false,
    isCommented: false,
  },
  {
    id: '10',
    profileImage: 'https://placekitten.com/109/109',
    nickname: 'Yuna',
    title: '초코 브라우니',
    views: 280,
    mainImage: 'https://placekitten.com/409/309',
    content: '진한 초콜릿 풍미 가득한 촉촉한 브라우니.',
    cookingTime: 45,
    difficulty: '보통',
    ingredientsCount: 8,
    likes: 175,
    bookmarks: 70,
    comments: 28,
    isLiked: false,
    isBookmarked: false,
    isCommented: false,
  },
  {
    id: '11',
    profileImage: 'https://placekitten.com/110/110',
    nickname: 'Taemin',
    title: '비빔밥',
    views: 540,
    mainImage: 'https://placekitten.com/410/310',
    content: '다양한 채소와 고소한 고추장 양념이 어우러진 건강식.',
    cookingTime: 25,
    difficulty: '보통',
    ingredientsCount: 12,
    likes: 250,
    bookmarks: 95,
    comments: 40,
    isLiked: false,
    isBookmarked: false,
    isCommented: false,
  },
  {
    id: '12',
    profileImage: 'https://placekitten.com/111/111',
    nickname: 'Lina',
    title: '팬케이크',
    views: 200,
    mainImage: 'https://placekitten.com/411/311',
    content: '부드럽고 달콤한 아침 메뉴, 메이플 시럽 듬뿍!',
    cookingTime: 15,
    difficulty: '쉬움',
    ingredientsCount: 6,
    likes: 130,
    bookmarks: 45,
    comments: 18,
    isLiked: false,
    isBookmarked: false,
    isCommented: false,
  },
  {
    id: '13',
    profileImage: 'https://placekitten.com/112/112',
    nickname: 'Hyunwoo',
    title: '삼겹살 구이',
    views: 890,
    mainImage: 'https://placekitten.com/412/312',
    content: '한국인의 사랑, 삼겹살! 쌈과 함께 즐기세요.',
    cookingTime: 30,
    difficulty: '쉬움',
    ingredientsCount: 4,
    likes: 520,
    bookmarks: 180,
    comments: 90,
    isLiked: false,
    isBookmarked: false,
    isCommented: false,
  },
  {
    id: '14',
    profileImage: 'https://placekitten.com/113/113',
    nickname: 'Olivia',
    title: '크로아상',
    views: 310,
    mainImage: 'https://placekitten.com/413/313',
    content: '겹겹이 버터 향 가득한 프랑스식 크로아상.',
    cookingTime: 60,
    difficulty: '어려움',
    ingredientsCount: 6,
    likes: 145,
    bookmarks: 55,
    comments: 22,
    isLiked: false,
    isBookmarked: false,
    isCommented: false,
  },
  {
    id: '15',
    profileImage: 'https://placekitten.com/114/114',
    nickname: 'Daniel',
    title: '라멘',
    views: 420,
    mainImage: 'https://placekitten.com/414/314',
    content: '진한 육수와 쫄깃한 면발이 일품인 일본식 라멘.',
    cookingTime: 40,
    difficulty: '보통',
    ingredientsCount: 10,
    likes: 260,
    bookmarks: 100,
    comments: 47,
    isLiked: false,
    isBookmarked: false,
    isCommented: false,
  },
  {
    id: '16',
    profileImage: 'https://placekitten.com/115/115',
    nickname: 'Hyejin',
    title: '닭강정',
    views: 370,
    mainImage: 'https://placekitten.com/415/315',
    content: '달콤하고 바삭한 닭강정, 남녀노소 모두 좋아하는 간식!',
    cookingTime: 35,
    difficulty: '보통',
    ingredientsCount: 9,
    likes: 190,
    bookmarks: 77,
    comments: 30,
    isLiked: false,
    isBookmarked: false,
    isCommented: false,
  },
  {
    id: '17',
    profileImage: 'https://placekitten.com/116/116',
    nickname: 'Jisoo',
    title: '샐러드',
    views: 210,
    mainImage: 'https://placekitten.com/416/316',
    content: '신선한 채소와 상큼한 드레싱이 어우러진 건강식.',
    cookingTime: 10,
    difficulty: '쉬움',
    ingredientsCount: 7,
    likes: 115,
    bookmarks: 40,
    comments: 16,
    isLiked: false,
    isBookmarked: false,
    isCommented: false,
  },
  {
    id: '18',
    profileImage: 'https://placekitten.com/117/117',
    nickname: 'Mark',
    title: '피자',
    views: 760,
    mainImage: 'https://placekitten.com/417/317',
    content: '바삭한 도우 위에 치즈와 토핑이 가득한 피자.',
    cookingTime: 25,
    difficulty: '보통',
    ingredientsCount: 8,
    likes: 490,
    bookmarks: 175,
    comments: 88,
    isLiked: false,
    isBookmarked: false,
    isCommented: false,
  },
  {
    id: '19',
    profileImage: 'https://placekitten.com/118/118',
    nickname: 'Sora',
    title: '케이크',
    views: 330,
    mainImage: 'https://placekitten.com/418/318',
    content: '생일에 빠질 수 없는 부드러운 크림 케이크.',
    cookingTime: 55,
    difficulty: '어려움',
    ingredientsCount: 10,
    likes: 210,
    bookmarks: 85,
    comments: 39,
    isLiked: false,
    isBookmarked: false,
    isCommented: false,
  },
  {
    id: '20',
    profileImage: 'https://placekitten.com/119/119',
    nickname: 'Leo',
    title: '샌드위치',
    views: 260,
    mainImage: 'https://placekitten.com/419/319',
    content: '든든한 한 끼로 좋은 간단 샌드위치.',
    cookingTime: 15,
    difficulty: '쉬움',
    ingredientsCount: 5,
    likes: 140,
    bookmarks: 50,
    comments: 21,
    isLiked: false,
    isBookmarked: false,
    isCommented: false,
  },
];
