/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Zipbap Service API
 * 집밥 서비스 전용 Swagger 문서
 * OpenAPI spec version: 1.0.1
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type { ApiResponseUserProfileDto, UpdateProfileParams } from '../zipbapServiceAPI.schemas';

export const getUserController = () => {
  const getProfile = <TData = AxiosResponse<ApiResponseUserProfileDto>>(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`https://zipbap.store/api/users/profile`, options);
  };
  const updateProfile = <TData = AxiosResponse<ApiResponseUserProfileDto>>(
    params: UpdateProfileParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.put(`https://zipbap.store/api/users/profile`, undefined, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  return { getProfile, updateProfile };
};
export type GetProfileResult = AxiosResponse<ApiResponseUserProfileDto>;
export type UpdateProfileResult = AxiosResponse<ApiResponseUserProfileDto>;
