/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Zipbap Service API
 * 집밥 서비스 전용 Swagger 문서
 * OpenAPI spec version: 1.0.1
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type {
  ApiResponseBookmarkSimpleResponseDto,
  ApiResponseListBookmarkRecipeResponseDto,
} from '../zipbapServiceAPI.schemas';

export const getBookmarkController = () => {
  const markRecipe = <TData = AxiosResponse<ApiResponseBookmarkSimpleResponseDto>>(
    recipeId: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(`https://zipbap.store/api/bookmarks/${recipeId}`, undefined, options);
  };
  const unmarkRecipe = <TData = AxiosResponse<ApiResponseBookmarkSimpleResponseDto>>(
    recipeId: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.delete(`https://zipbap.store/api/bookmarks/${recipeId}`, options);
  };
  const countBookmarks = <TData = AxiosResponse<ApiResponseBookmarkSimpleResponseDto>>(
    recipeId: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`https://zipbap.store/api/bookmarks/${recipeId}/count`, options);
  };
  const userRecipes = <TData = AxiosResponse<ApiResponseListBookmarkRecipeResponseDto>>(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`https://zipbap.store/api/bookmarks/users`, options);
  };
  return { markRecipe, unmarkRecipe, countBookmarks, userRecipes };
};
export type MarkRecipeResult = AxiosResponse<ApiResponseBookmarkSimpleResponseDto>;
export type UnmarkRecipeResult = AxiosResponse<ApiResponseBookmarkSimpleResponseDto>;
export type CountBookmarksResult = AxiosResponse<ApiResponseBookmarkSimpleResponseDto>;
export type UserRecipesResult = AxiosResponse<ApiResponseListBookmarkRecipeResponseDto>;
