/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Zipbap Service API
 * 집밥 서비스 전용 Swagger 문서
 * OpenAPI spec version: 1.0.1
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type {
  ApiResponseUnit,
  CommentDetailResponseDto,
  CreateCommentRequestDto,
  GetCommentsParams,
  UpdateCommentRequestDto,
} from '../zipbapServiceAPI.schemas';

export const getComment = () => {
  /**
   * 본인이 작성한 댓글 내용을 수정합니다.
   * @summary 댓글 수정
   */
  const updateComment = <TData = AxiosResponse<ApiResponseUnit>>(
    commentId: number,
    updateCommentRequestDto: UpdateCommentRequestDto,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.put(
      `https://zipbap.store/api/comments/${commentId}`,
      updateCommentRequestDto,
      options,
    );
  };
  /**
   * 본인이 작성한 댓글을 삭제합니다.
   * @summary 댓글 삭제
   */
  const deleteComment = <TData = AxiosResponse<ApiResponseUnit>>(
    commentId: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.delete(`https://zipbap.store/api/comments/${commentId}`, options);
  };
  /**
   * 레시피에 달린 모든 댓글과 대댓글을 조회합니다.
   * @summary 댓글 목록 조회
   */
  const getComments = <TData = AxiosResponse<CommentDetailResponseDto>>(
    params: GetCommentsParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`https://zipbap.store/api/comments`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  /**
   * 레시피에 댓글 또는 대댓글을 작성합니다.
   * @summary 댓글 작성
   */
  const createComment = <TData = AxiosResponse<CommentDetailResponseDto>>(
    createCommentRequestDto: CreateCommentRequestDto,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(`https://zipbap.store/api/comments`, createCommentRequestDto, options);
  };
  return { updateComment, deleteComment, getComments, createComment };
};
export type UpdateCommentResult = AxiosResponse<ApiResponseUnit>;
export type DeleteCommentResult = AxiosResponse<ApiResponseUnit>;
export type GetCommentsResult = AxiosResponse<CommentDetailResponseDto>;
export type CreateCommentResult = AxiosResponse<CommentDetailResponseDto>;
