/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Zipbap Service API
 * 집밥 서비스 전용 Swagger 문서
 * OpenAPI spec version: 1.0.1
 */
export interface CookingOrderRequest {
  /** 순서 */
  turn?: number;
  /** 이미지 URL */
  image?: string;
  /** 설명 */
  description?: string;
}

export interface UpdateTempRecipeRequestDto {
  /** 레시피 제목 */
  title?: string;
  /** 레시피 소제목 */
  subtitle?: string;
  /** 레시피 소개 */
  introduction?: string;
  /** 내 레시피(해당 사용자 전용) */
  myCategoryId?: string;
  /** 요리종류 ID */
  cookingTypeId?: number;
  /** 상황 카테고리 ID */
  situationId?: number;
  /** 주재료 카테고리 ID */
  mainIngredientId?: number;
  /** 조리방법 카테고리 ID */
  methodId?: number;
  /** 인분(인원수) 카테고리 ID */
  headcountId?: number;
  /** 요리 시간 카테고리 ID */
  cookingTimeId?: number;
  /** 난이도 카테고리 ID */
  levelId?: number;
  /** 재료 정보 */
  ingredientInfo?: string;
  /** 요리 킥 */
  kick?: string;
  /** 비공개 여부 */
  isPrivate?: boolean;
  /** 조리 순서 목록 */
  cookingOrders?: CookingOrderRequest[];
  /** 영상 URL */
  video?: string;
}

export interface CookingOrderResponse {
  /** 순서 */
  turn: number;
  /** 이미지 URL */
  image?: string;
  /** 설명 */
  description?: string;
}

export interface TempRecipeDetailResponseDto {
  /** 레시피 ID */
  id: string;
  /** 레시피 제목 */
  title?: string;
  /** 레시피 소제목 */
  subtitle?: string;
  /** 레시피 소개 */
  introduction?: string;
  /** 내 레시피(해당 사용자 전용) */
  myCategoryId?: string;
  /** 요리종류 ID */
  cookingTypeId?: number;
  /** 상황 카테고리 ID */
  situationId?: number;
  /** 주재료 카테고리 ID */
  mainIngredientId?: number;
  /** 조리방법 카테고리 ID */
  methodId?: number;
  /** 인분(인원수) 카테고리 ID */
  headcountId?: number;
  /** 요리 시간 카테고리 ID */
  cookingTimeId?: number;
  /** 난이도 카테고리 ID */
  levelId?: number;
  /** 재료 정보 */
  ingredientInfo?: string;
  /** 요리 킥 */
  kick?: string;
  /** 비공개 여부 */
  isPrivate?: boolean;
  /** 조리 순서 목록 */
  cookingOrders: CookingOrderResponse[];
  /** 영상 URL */
  video?: string;
}

export interface FinalizeRecipeRequestDto {
  /** 레시피 제목 */
  title: string;
  /** 레시피 소제목 */
  subtitle: string;
  /** 레시피 소개 */
  introduction: string;
  /** 내 레시피(해당 사용자 전용) */
  myCategoryId?: string;
  /** 요리종류 ID */
  cookingTypeId: number;
  /** 상황 카테고리 ID */
  situationId: number;
  /** 주재료 카테고리 ID */
  mainIngredientId: number;
  /** 조리방법 카테고리 ID */
  methodId: number;
  /** 인분(인원수) 카테고리 ID */
  headcountId: number;
  /** 요리 시간 카테고리 ID */
  cookingTimeId: number;
  /** 난이도 카테고리 ID */
  levelId: number;
  /** 재료 정보 */
  ingredientInfo: string;
  /** 요리 킥 */
  kick?: string;
  /** 비공개 여부 */
  isPrivate: boolean;
  /** 조리 순서 목록 */
  cookingOrders: CookingOrderRequest[];
  /** 영상 URL */
  video?: string;
}

export interface RecipeDetailResponseDto {
  /** 레시피 ID */
  id: string;
  /** 레시피 제목 */
  title: string;
  /** 레시피 소제목 */
  subtitle: string;
  /** 레시피 소개 */
  introduction: string;
  /** 내 레시피(해당 사용자 전용) */
  myCategoryId?: string;
  /** 요리종류 ID */
  cookingTypeId: number;
  /** 상황 카테고리 ID */
  situationId: number;
  /** 주재료 카테고리 ID */
  mainIngredientId: number;
  /** 조리방법 카테고리 ID */
  methodId: number;
  /** 인분(인원수) 카테고리 ID */
  headcountId: number;
  /** 요리 시간 카테고리 ID */
  cookingTimeId: number;
  /** 난이도 카테고리 ID */
  levelId: number;
  /** 재료 정보 */
  ingredientInfo: string;
  /** 요리 킥 */
  kick?: string;
  /** 비공개 여부 */
  isPrivate: boolean;
  /** 조리 순서 목록 */
  cookingOrders: CookingOrderResponse[];
  /** 영상 URL */
  video?: string;
}

/**
 * 내 카테고리 수정 요청 DTO
 */
export interface UpdateMyCategoryDto {
  /**
   * 내 카테고리 명칭
   * @minLength 0
   * @maxLength 20
   */
  name?: string;
}

export interface ApiResponseMyCategoryResponseDto {
  isSuccess: boolean;
  code?: string;
  message?: string;
  result?: MyCategoryResponseDto;
}

/**
 * 내 카테고리 응답 DTO
 */
export interface MyCategoryResponseDto {
  /** ID */
  id: string;
  /** 내 카테고리 명칭 */
  name: string;
}

/**
 * 내 카테고리 생성 요청 DTO
 */
export interface CreateMyCategoryDto {
  /**
   * 내 카테고리 명칭
   * @minLength 0
   * @maxLength 20
   */
  name: string;
}

export interface PresignedUrlRequest {
  /** 파일명 */
  fileName: string;
}

export interface PresignedUrlResponse {
  /** 업로드용 Presigned URL */
  uploadUrl: string;
  /** 업로드된 파일 접근 URL */
  fileUrl: string;
}

/**
 * 카테고리 항목 DTO
 */
export interface CategoryItemDto {
  /** 카테고리 ID */
  id?: number;
  /** 카테고리 이름/값 */
  name: string;
}

export interface CategoryListResponseDto {
  /** 요리 시간 목록 */
  cookingTimes: CategoryItemDto[];
  /** 요리 종류 목록 */
  cookingTypes: CategoryItemDto[];
  /** 인원 수 목록 */
  headcounts: CategoryItemDto[];
  /** 난이도 목록 */
  levels: CategoryItemDto[];
  /** 주재료 목록 */
  mainIngredients: CategoryItemDto[];
  /** 조리 방법 목록 */
  methods: CategoryItemDto[];
  /** 상황별 요리 목록 */
  situations: CategoryItemDto[];
  /** 내 카테고리 목록 */
  myCategories: MyCategoryItemDto[];
}

/**
 * 내 카테고리 항목 DTO
 */
export interface MyCategoryItemDto {
  /** 내 카테고리 ID */
  id: string;
  /** 내 카테고리 이름 */
  name: string;
}

export interface ApiResponseListMyCategoryResponseDto {
  isSuccess: boolean;
  code?: string;
  message?: string;
  result?: MyCategoryResponseDto[];
}

export interface ApiResponseObject {
  isSuccess: boolean;
  code?: string;
  message?: string;
  result?: unknown;
}

export interface ApiResponseUnit {
  isSuccess: boolean;
  code?: string;
  message?: string;
}

export type UpdateTempRecipeParams = {
  userId: number;
};

export type FinalizeRecipeParams = {
  userId: number;
};

export type UpdateMyCategoryParams = {
  userId: number;
};

export type DeleteMyCategoryParams = {
  userId: number;
};

export type GetMyTempRecipesParams = {
  userId: number;
};

export type CreateTempRecipeParams = {
  userId: number;
};

export type GetMyCategoriesParams = {
  userId: number;
};

export type CreateMyCategoryParams = {
  userId: number;
};

export type GetAllCategoriesParams = {
  /**
   * 사용자 ID
   */
  userId: number;
};

export type GetMyRecipesParams = {
  userId: number;
};
