/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Zipbap Service API
 * 집밥 서비스 전용 Swagger 문서
 * OpenAPI spec version: 1.0.1
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type { ApiResponseObject } from '../zipbapServiceAPI.schemas';

export const getAuthController = () => {
  const getAccessToken = <TData = AxiosResponse<ApiResponseObject>>(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`https://zipbap.store/api/auth/access-token`, options);
  };
  return { getAccessToken };
};
export type GetAccessTokenResult = AxiosResponse<ApiResponseObject>;
