/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Zipbap Service API
 * 집밥 서비스 전용 Swagger 문서
 * OpenAPI spec version: 1.0.1
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type {
  ApiResponseListMyCategoryResponseDto,
  ApiResponseMyCategoryResponseDto,
  ApiResponseUnit,
  CreateMyCategoryDto,
  CreateMyCategoryParams,
  DeleteMyCategoryParams,
  GetMyCategoriesParams,
  UpdateMyCategoryDto,
  UpdateMyCategoryParams,
} from '../zipbapServiceAPI.schemas';

export const getMyCategories = () => {
  const updateMyCategory = <TData = AxiosResponse<ApiResponseMyCategoryResponseDto>>(
    id: string,
    updateMyCategoryDto: UpdateMyCategoryDto,
    params: UpdateMyCategoryParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.put(`https://zipbap.store/api/my-categories/${id}`, updateMyCategoryDto, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  const deleteMyCategory = <TData = AxiosResponse<ApiResponseUnit>>(
    id: string,
    params: DeleteMyCategoryParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.delete(`https://zipbap.store/api/my-categories/${id}`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  const getMyCategories = <TData = AxiosResponse<ApiResponseListMyCategoryResponseDto>>(
    params: GetMyCategoriesParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`https://zipbap.store/api/my-categories`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  const createMyCategory = <TData = AxiosResponse<ApiResponseMyCategoryResponseDto>>(
    createMyCategoryDto: CreateMyCategoryDto,
    params: CreateMyCategoryParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(`https://zipbap.store/api/my-categories`, createMyCategoryDto, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  return { updateMyCategory, deleteMyCategory, getMyCategories, createMyCategory };
};
export type UpdateMyCategoryResult = AxiosResponse<ApiResponseMyCategoryResponseDto>;
export type DeleteMyCategoryResult = AxiosResponse<ApiResponseUnit>;
export type GetMyCategoriesResult = AxiosResponse<ApiResponseListMyCategoryResponseDto>;
export type CreateMyCategoryResult = AxiosResponse<ApiResponseMyCategoryResponseDto>;
