/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Zipbap Service API
 * 집밥 서비스 전용 Swagger 문서
 * OpenAPI spec version: 1.0.1
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type {
  FeedDetailResponseDto,
  FeedItemResponseDto,
  GetFeedParams,
} from '../zipbapServiceAPI.schemas';

export const getFeed = () => {
  /**
 * 
조건에 따라 피드 목록을 페이징해서 가져옵니다.  
무한 스크롤 시 `page` 값만 증가시켜 호출하면 됩니다.  

📌 파라미터 설명  
- **filter (string, query)**  
  - 피드 조회 조건 (기본값: `ALL`)  
  - `ALL`: 전체  
  - `TODAY`: 오늘 올린 글만  
  - `HOT`: 좋아요 많은 순  
  - `RECOMMEND`: 북마크 많은 순  
  - `FOLLOWING`: 내가 팔로잉한 사람 글만 (로그인 필요)  

- **page (int, query)**  
  - 페이지 번호 (0부터 시작)  
  - 예: `page=0` → 첫 페이지, `page=1` → 두 번째 페이지  

- **size (int, query)**  
  - 한 페이지에 가져올 데이터 개수 (기본값: 20)  
  - 예: `size=10` → 10개씩 불러오기  

- **sort (array, query)**  
  - 정렬 조건 (기본값: `createdAt,desc`)  
  - 형식: `property,(asc|desc)`  
  - 예: `sort=createdAt,desc` → 최신순  
  - 예: `sort=likeCount,desc` → 좋아요 많은 순  
  - 여러 조건 가능 → `sort=likeCount,desc&sort=createdAt,desc`  

📌 호출 예시  
- `/api/feed?filter=ALL&page=0&size=10&sort=createdAt,desc`  
- `/api/feed?filter=HOT&page=1&size=20&sort=likeCount,desc`

 * @summary 피드 목록 조회
 */
  const getFeed = <TData = AxiosResponse<FeedItemResponseDto[]>>(
    params?: GetFeedParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`https://zipbap.store/api/feed`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  /**
 * 
특정 레시피의 상세 피드 정보를 조회합니다.  

📌 파라미터 설명  
- **user**: 로그인 사용자 (없으면 null)  
- **recipeId**: 조회할 레시피 ID (예: RC-1-00001)  

📌 호출 예시  
- `/api/feed/RC-1-00001`

 * @summary 피드 상세 조회
 */
  const getFeedDetail = <TData = AxiosResponse<FeedDetailResponseDto>>(
    recipeId: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`https://zipbap.store/api/feed/${recipeId}`, options);
  };
  return { getFeed, getFeedDetail };
};
export type GetFeedResult = AxiosResponse<FeedItemResponseDto[]>;
export type GetFeedDetailResult = AxiosResponse<FeedDetailResponseDto>;
